### ISSUE TITLE
CommandBar Icons don't show up on Windows 10

### ISSUE THREAD

**Issue by michael-hawker** [zateutsch/ML-Playground#4]
![image](https://user-images.githubusercontent.com/24302614/143926353-ab40685a-4759-4065-ab72-527a23201255.png)

Same once you go in the model page.

Looks like this font isn't included in Win10 by default: https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#how-do-i-get-this-font

Not sure what that means for app developers?

**Comment by zateutsch** [comment]
Resolved by using {ThemeResource SymbolThemeFontFamily} for icon FontFamily.
